In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [4]:
arr1 = np.arange(9).reshape(3,3)

In [5]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [7]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
ser1 = Series([0,1,2], index=['T', 'U', 'V'])
ser2 = Series([3,4],['X', 'Y'])

In [9]:
ser1

T    0
U    1
V    2
dtype: int64

In [10]:
ser2

X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1, ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [13]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [14]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])

In [15]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y', 'Q', 'X'])

In [16]:
dframe1

X         Y         Z
0  1.062219 -1.046439 -0.404783
1  0.110550  0.929425 -1.233344
2 -0.017591 -1.710478 -1.749479
3 -0.489251  0.498962 -0.249834

In [17]:
dframe2

Y         Q         X
0 -0.095967 -0.210703  0.855903
1  0.235917  0.352921 -0.486986
2  2.189498  0.628144  0.879575

In [18]:
pd.concat([dframe1, dframe2])

Q         X         Y         Z
0       NaN  1.062219 -1.046439 -0.404783
1       NaN  0.110550  0.929425 -1.233344
2       NaN -0.017591 -1.710478 -1.749479
3       NaN -0.489251  0.498962 -0.249834
0 -0.210703  0.855903 -0.095967       NaN
1  0.352921 -0.486986  0.235917       NaN
2  0.628144  0.879575  2.189498       NaN

In [19]:
pd.concat([dframe1, dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN  1.062219 -1.046439 -0.404783
1       NaN  0.110550  0.929425 -1.233344
2       NaN -0.017591 -1.710478 -1.749479
3       NaN -0.489251  0.498962 -0.249834
4 -0.210703  0.855903 -0.095967       NaN
5  0.352921 -0.486986  0.235917       NaN
6  0.628144  0.879575  2.189498       NaN